name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run lint
        run: npm run lint

  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.2.6

      - name: Cache dependencies
        run: deno cache source/cli.tsx

      - name: Run tests
        run: deno test --allow-read --allow-write --allow-net --allow-env --allow-run --allow-sys

      - name: Run lint
        run: deno lint

      - name: Run format check
        run: deno fmt --check
