name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Build Node.js version
        run: |
          npm run build
          npm run postbuild

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.2.6

      - name: Install Deno dependencies
        run: deno cache source/cli.deno.tsx

      - name: Build Deno version
        run: deno task build

      - name: Upload Node.js artifact
        uses: actions/upload-artifact@v4
        with:
          name: permit-cli-node
          path: dist/
          retention-days: 7

      - name: Upload Deno artifact
        uses: actions/upload-artifact@v4
        with:
          name: permit-cli-deno
          path: permit-cli
          retention-days: 7
