name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.2.6

      - name: Regenerate lock file
        run: deno cache --reload source/cli.tsx

      - name: Install dependencies
        run: deno cache source/cli.tsx

      - name: Build
        run: deno task build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: permit-cli
          path: permit-cli
          retention-days: 7
